//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using CapaEntidad;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalProg2Entities : DbContext
    {
        public FinalProg2Entities()
            : base("name=FinalProg2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<nomina> nomina { get; set; }
        public virtual DbSet<licencia> licencia { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<salidas> salidas { get; set; }
        public virtual DbSet<vacaciones> vacaciones { get; set; }
    }
}
