//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacaciones
    {
        public string empleado { get; set; }
        public string fecha_comienzo_vacaciones { get; set; }
        public string fecha_final_vacaciones { get; set; }
        public string año { get; set; }
        public string comentarios { get; set; }
    }
}
